-- Seed 27 Data Quality Rules in silver.dq_rule
INSERT INTO silver.dq_rule (rule_id, layer, target_object, expression, severity, threshold, is_active, linked_finding, description)
VALUES
    ('DQ-R01', 'silver', 'slv_customer', 'customer_id IS NOT NULL', 'BLOCK', 0.0000, true, 'BR-R1', 'Customer ID must not be null'),
    ('DQ-R02', 'silver', 'slv_customer', 'created_at IS NOT NULL AND created_at <= NOW()', 'BLOCK', 0.0000, true, 'BR-R2', 'Customer creation date must be valid and not in future'),
    ('DQ-R03', 'silver', 'slv_order', 'order_id IS NOT NULL', 'BLOCK', 0.0000, true, 'BR-R3', 'Order ID must not be null'),
    ('DQ-R04', 'silver', 'slv_order', 'order_status IN (''PLACED'', \'CONFIRMED\', \'PREPARING\', \'OUT_FOR_DELIVERY\', \'DELIVERED\', \'CANCELLED\')', 'BLOCK', 0.0100, true, 'BR-R4', 'Order status must be known conformed value'),
    ('DQ-R05', 'silver', 'slv_customer', 'email IS NULL OR email LIKE ''%@%.%''', 'WARN', 0.0500, true, 'BR-R5', 'Customer email format validation'),
    ('DQ-R06', 'silver', 'slv_customer', 'phone IS NULL OR LENGTH(phone) >= 10', 'WARN', 0.0500, true, 'BR-R6', 'Customer phone format validation'),
    ('DQ-R07', 'silver', 'slv_order', 'total_amount >= 0', 'BLOCK', 0.0000, true, 'BR-R7', 'Order total amount must be non-negative'),
    ('DQ-R08', 'silver', 'slv_order_item', 'unit_price >= 0 AND quantity > 0', 'BLOCK', 0.0000, true, 'BR-R8', 'Order item price non-negative and quantity positive'),
    ('DQ-R09', 'silver', 'slv_payment', 'payment_id IS NOT NULL', 'BLOCK', 0.0000, true, 'BR-R9', 'Payment ID must not be null'),
    ('DQ-R10', 'silver', 'slv_payment', 'amount >= 0', 'BLOCK', 0.0000, true, 'BR-R10', 'Payment amount must be non-negative'),
    ('DQ-R11', 'silver', 'slv_restaurant', 'restaurant_id IS NOT NULL', 'BLOCK', 0.0000, true, 'BR-R11', 'Restaurant ID must not be null'),
    ('DQ-R12', 'silver', 'slv_restaurant', 'is_active IS NOT NULL', 'WARN', 0.0100, true, 'BR-R12', 'Restaurant active status must be specified'),
    ('DQ-R13', 'silver', 'slv_order', 'customer_id IS NOT NULL', 'BLOCK', 0.0100, true, 'BR-R13', 'Order must reference valid customer ID'),
    ('DQ-R14', 'silver', 'slv_order', 'restaurant_id IS NOT NULL', 'BLOCK', 0.0100, true, 'BR-R14', 'Order must reference valid restaurant ID'),
    ('DQ-R15', 'silver', 'slv_payment', 'order_id IS NOT NULL', 'BLOCK', 0.0100, true, 'BR-R15', 'Payment must reference valid order ID'),
    ('DQ-R16', 'silver', 'slv_delivery', 'order_id IS NOT NULL', 'BLOCK', 0.0100, true, 'BR-R16', 'Delivery must reference valid order ID'),
    ('DQ-R17', 'silver', 'slv_delivery', 'delivery_status IN (''ASSIGNED'', \'PICKED_UP\', \'DELIVERED\', \'FAILED\', \'CANCELLED\')', 'BLOCK', 0.0100, true, 'BR-R17', 'Delivery status conformed value check'),
    ('DQ-R18', 'silver', 'slv_order_item', 'item_total >= 0', 'BLOCK', 0.0000, true, 'BR-R18', 'Order item total must be non-negative'),
    ('DQ-R19', 'silver', 'slv_delivery_partner', 'partner_id IS NOT NULL', 'BLOCK', 0.0000, true, 'BR-R19', 'Delivery partner ID must not be null'),
    ('DQ-R20', 'silver', 'slv_menu_item', 'item_id IS NOT NULL', 'BLOCK', 0.0000, true, 'BR-R20', 'Menu item ID must not be null'),
    ('DQ-R21', 'gold', 'fact_order', 'customer_sk <> -1', 'WARN', 0.0500, true, 'BR-R21', 'Gold Fact order customer dimension resolution'),
    ('DQ-R22', 'gold', 'fact_order', 'restaurant_sk <> -1', 'WARN', 0.0500, true, 'BR-R22', 'Gold Fact order restaurant dimension resolution'),
    ('DQ-R23', 'gold', 'fact_order', 'total_amount >= 0', 'BLOCK', 0.0000, true, 'BR-R23', 'Gold Fact order total amount non-negative'),
    ('DQ-R24', 'gold', 'dim_customer', 'valid_from <= COALESCE(valid_to, ''9999-12-31''::timestamptz)', 'BLOCK', 0.0000, true, 'BR-R24', 'SCD2 Customer effective dates valid'),
    ('DQ-R25', 'gold', 'dim_restaurant', 'valid_from <= COALESCE(valid_to, ''9999-12-31''::timestamptz)', 'BLOCK', 0.0000, true, 'BR-R25', 'SCD2 Restaurant effective dates valid'),
    ('DQ-R26', 'gold', 'fact_delivery', 'order_sk <> -1', 'WARN', 0.0500, true, 'BR-R26', 'Gold Fact delivery order resolution'),
    ('DQ-R27', 'gold', 'mart_daily_business_summary', 'total_orders >= 0', 'BLOCK', 0.0000, true, 'BR-R27', 'Business summary total orders non-negative')
ON CONFLICT (rule_id) DO UPDATE SET
    layer = EXCLUDED.layer,
    target_object = EXCLUDED.target_object,
    expression = EXCLUDED.expression,
    severity = EXCLUDED.severity,
    threshold = EXCLUDED.threshold,
    is_active = EXCLUDED.is_active,
    linked_finding = EXCLUDED.linked_finding,
    description = EXCLUDED.description;
